module.exports = {
    ci: {
        collect: {
            // Configurazione per il build e preview
            startServerCommand: 'npm run preview',
            startServerReadyPattern: 'Local:',
            startServerReadyTimeout: 10000,
            url: [
                'http://localhost:4173/',
                'http://localhost:4173/blog',
                'http://localhost:4173/portfolio',
                'http://localhost:4173/contact'
            ],
            numberOfRuns: 3,
            settings: {
                chromeFlags: '--no-sandbox --disable-dev-shm-usage --disable-gpu',
                onlyCategories: ['accessibility', 'performance', 'best-practices', 'seo'],
                formFactor: 'desktop',
                throttling: {
                    rttMs: 40,
                    throughputKbps: 10240,
                    cpuSlowdownMultiplier: 1,
                    requestLatencyMs: 0,
                    downloadThroughputKbps: 0,
                    uploadThroughputKbps: 0
                },
                screenEmulation: {
                    mobile: false,
                    width: 1350,
                    height: 940,
                    deviceScaleFactor: 1,
                    disabled: false
                },
                emulatedUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            }
        },
        assert: {
            assertions: {
                // Accessibilità - deve essere ≥ 95
                'categories:accessibility': ['error', { minScore: 0.95 }],
                // Performance - deve essere ≥ 90
                'categories:performance': ['warn', { minScore: 0.90 }],
                // Best Practices - deve essere ≥ 90
                'categories:best-practices': ['warn', { minScore: 0.90 }],
                // SEO - deve essere ≥ 90
                'categories:seo': ['warn', { minScore: 0.90 }],

                // Regole specifiche di accessibilità
                'accessibility/color-contrast': 'warn',
                'accessibility/document-title': 'error',
                'accessibility/html-has-lang': 'error',
                'accessibility/html-lang-valid': 'error',
                'accessibility/landmark-one-main': 'error',
                'accessibility/page-has-heading-one': 'error',
                'accessibility/region': 'warn',
                'accessibility/skip-link': 'warn',
                'accessibility/focus-order-semantics': 'warn',
                'accessibility/focus-visible': 'warn',
                'accessibility/target-size': 'warn',
                'accessibility/button-name': 'error',
                'accessibility/image-alt': 'error',
                'accessibility/link-name': 'error',
                'accessibility/list': 'error',
                'accessibility/listitem': 'error',
                'accessibility/definition-list': 'warn',
                'accessibility/dlitem': 'warn',
                'accessibility/frame-title': 'error',
                'accessibility/frame-title-unique': 'warn',
                'accessibility/iframe-title': 'error',
                'accessibility/form-field-multiple-labels': 'warn',
                'accessibility/label': 'error',
                'accessibility/label-title-only': 'warn',
                'accessibility/aria-required-attr': 'error',
                'accessibility/aria-required-children': 'error',
                'accessibility/aria-required-parent': 'error',
                'accessibility/aria-roles': 'error',
                'accessibility/aria-valid-attr-value': 'error',
                'accessibility/aria-valid-attr': 'error',
                'accessibility/aria-allowed-attr': 'error',
                'accessibility/aria-allowed-role': 'error',
                'accessibility/aria-hidden-body': 'error',
                'accessibility/aria-hidden-focus': 'error',
                'accessibility/aria-input-field-name': 'error',
                'accessibility/aria-toggle-field-name': 'error',
                'accessibility/aria-treeitem-name': 'error',
                'accessibility/aria-command-name': 'error',
                'accessibility/aria-meter-name': 'error',
                'accessibility/aria-progressbar-name': 'error',
                'accessibility/aria-slider-name': 'error',
                'accessibility/aria-spinbutton-name': 'error',
                'accessibility/aria-switch-name': 'error',
                'accessibility/aria-tabindex': 'error',
                'accessibility/aria-unsupported-elements': 'error',
                'accessibility/duplicate-id': 'error',
                'accessibility/duplicate-id-active': 'error',
                'accessibility/duplicate-id-aria': 'error',
                'accessibility/heading-order': 'warn',
                'accessibility/meta-viewport': 'error',
                'accessibility/object-alt': 'error',
                'accessibility/presentation-role-conflict': 'error',
                'accessibility/scope-attr-valid': 'error',
                'accessibility/server-side-image-map': 'error',
                'accessibility/svg-img-alt': 'error',
                'accessibility/td-headers-attr': 'error',
                'accessibility/th-has-data-cells': 'error',
                'accessibility/valid-lang': 'error',
                'accessibility/video-caption': 'warn',
                'accessibility/video-description': 'warn',
                'accessibility/autocomplete-valid': 'warn',
                'accessibility/avoid-inline-spacing': 'warn',
                'accessibility/bypass': 'error',
                'accessibility/empty-heading': 'warn',
                'accessibility/empty-table-header': 'warn',
                'accessibility/form-field-multiple-labels': 'warn',
                'accessibility/frame-focusable-content': 'error',
                'accessibility/image-redundant-alt': 'warn',
                'accessibility/marquee': 'error',
                'accessibility/meta-refresh': 'error',
                'accessibility/presentation-role-conflict': 'error',
                'accessibility/tabindex': 'error',
                'accessibility/table-duplicate-name': 'error',
                'accessibility/table-fake-caption': 'error',
                'accessibility/td-has-header': 'error',
                'accessibility/valid-lang': 'error',

                // Performance critiche
                'performance/first-contentful-paint': ['warn', { maxNumericValue: 2000 }],
                'performance/largest-contentful-paint': ['warn', { maxNumericValue: 2500 }],
                'performance/first-meaningful-paint': ['warn', { maxNumericValue: 2000 }],
                'performance/speed-index': ['warn', { maxNumericValue: 3000 }],
                'performance/interactive': ['warn', { maxNumericValue: 3500 }],
                'performance/total-blocking-time': ['warn', { maxNumericValue: 300 }],
                'performance/cumulative-layout-shift': ['warn', { maxNumericValue: 0.1 }],

                // Best Practices
                'best-practices/uses-https': 'error',
                'best-practices/uses-http2': 'warn',
                'best-practices/no-document-write': 'error',
                'best-practices/external-anchors-use-rel-noopener': 'error',
                'best-practices/geolocation-on-start': 'error',
                'best-practices/no-vulnerable-libraries': 'error',
                'best-practices/notification-on-start': 'error',
                'best-practices/no-password-inputs-can-be-pasted-into': 'error',
                'best-practices/uses-passive-event-listeners': 'warn',
                'best-practices/meta-charset-utf-8': 'error',
                'best-practices/meta-viewport': 'error',
                'best-practices/object-alt': 'error',
                'best-practices/valid-source-maps': 'warn',
                'best-practices/uses-text-compression': 'warn',
                'best-practices/uses-long-cache-ttl': 'warn',
                'best-practices/non-composited-animations': 'warn',
                'best-practices/unsized-images': 'warn',
                'best-practices/no-unused-css-rules': 'warn',
                'best-practices/no-unused-javascript': 'warn',
                'best-practices/uses-optimized-images': 'warn',
                'best-practices/uses-webp-images': 'warn',
                'best-practices/uses-responsive-images': 'warn',
                'best-practices/efficient-animated-content': 'warn',
                'best-practices/appcache-manifest': 'error',
                'best-practices/errors-in-console': 'error',
                'best-practices/image-aspect-ratio': 'warn',
                'best-practices/import-on-interaction': 'warn',
                'best-practices/link-text': 'error',
                'best-practices/manual/password-inputs-can-be-pasted-into': 'error',
                'best-practices/manual/uses-long-cache-ttl': 'warn',
                'best-practices/manual/uses-text-compression': 'warn',
                'best-practices/manual/uses-optimized-images': 'warn',
                'best-practices/manual/uses-webp-images': 'warn',
                'best-practices/manual/uses-responsive-images': 'warn',
                'best-practices/manual/uses-rel-preconnect': 'warn',
                'best-practices/manual/uses-rel-preload': 'warn',
                'best-practices/manual/uses-http2': 'warn',
                'best-practices/manual/uses-passive-event-listeners': 'warn',
                'best-practices/manual/no-document-write': 'error',
                'best-practices/manual/no-vulnerable-libraries': 'error',
                'best-practices/manual/external-anchors-use-rel-noopener': 'error',
                'best-practices/manual/geolocation-on-start': 'error',
                'best-practices/manual/notification-on-start': 'error',
                'best-practices/manual/no-password-inputs-can-be-pasted-into': 'error',
                'best-practices/manual/uses-https': 'error',
                'best-practices/manual/meta-charset-utf-8': 'error',
                'best-practices/manual/meta-viewport': 'error',
                'best-practices/manual/object-alt': 'error',
                'best-practices/manual/valid-source-maps': 'warn',
                'best-practices/manual/non-composited-animations': 'warn',
                'best-practices/manual/unsized-images': 'warn',
                'best-practices/manual/no-unused-css-rules': 'warn',
                'best-practices/manual/no-unused-javascript': 'warn',
                'best-practices/manual/efficient-animated-content': 'warn',
                'best-practices/manual/appcache-manifest': 'error',
                'best-practices/manual/errors-in-console': 'error',
                'best-practices/manual/image-aspect-ratio': 'warn',
                'best-practices/manual/import-on-interaction': 'warn',
                'best-practices/manual/link-text': 'error',

                // SEO
                'seo/meta-description': 'error',
                'seo/link-text': 'error',
                'seo/image-alt': 'error',
                'seo/heading-elements': 'error',
                'seo/input-image-alt': 'error',
                'seo/image-title': 'warn',
                'seo/button-name': 'error',
                'seo/frame-title': 'error',
                'seo/input-image-alt': 'error',
                'seo/is-crawlable': 'error',
                'seo/robots-txt': 'warn',
                'seo/hreflang': 'warn',
                'seo/plugins': 'error',
                'seo/canonical': 'warn',
                'seo/font-size': 'error',
                'seo/tap-targets': 'error',
                'seo/structured-data': 'warn',
                'seo/uses-text-compression': 'warn',
                'seo/uses-long-cache-ttl': 'warn',
                'seo/total-byte-weight': 'warn',
                'seo/uses-optimized-images': 'warn',
                'seo/uses-webp-images': 'warn',
                'seo/uses-responsive-images': 'warn',
                'seo/efficient-animated-content': 'warn',
                'seo/appcache-manifest': 'error',
                'seo/errors-in-console': 'error',
                'seo/image-aspect-ratio': 'warn',
                'seo/import-on-interaction': 'warn',
                'seo/link-text': 'error',
                'seo/manual/meta-description': 'error',
                'seo/manual/link-text': 'error',
                'seo/manual/image-alt': 'error',
                'seo/manual/heading-elements': 'error',
                'seo/manual/input-image-alt': 'error',
                'seo/manual/image-title': 'warn',
                'seo/manual/button-name': 'error',
                'seo/manual/frame-title': 'error',
                'seo/manual/is-crawlable': 'error',
                'seo/manual/robots-txt': 'warn',
                'seo/manual/hreflang': 'warn',
                'seo/manual/plugins': 'error',
                'seo/manual/canonical': 'warn',
                'seo/manual/font-size': 'error',
                'seo/manual/tap-targets': 'error',
                'seo/manual/structured-data': 'warn',
                'seo/manual/uses-text-compression': 'warn',
                'seo/manual/uses-long-cache-ttl': 'warn',
                'seo/manual/total-byte-weight': 'warn',
                'seo/manual/uses-optimized-images': 'warn',
                'seo/manual/uses-webp-images': 'warn',
                'seo/manual/uses-responsive-images': 'warn',
                'seo/manual/efficient-animated-content': 'warn',
                'seo/manual/appcache-manifest': 'error',
                'seo/manual/errors-in-console': 'error',
                'seo/manual/image-aspect-ratio': 'warn',
                'seo/manual/import-on-interaction': 'warn',
                'seo/manual/link-text': 'error'
            }
        },
        upload: {
            target: 'temporary-public-storage',
            outputDir: './lighthouse-results'
        }
    }
};
